### ISSUE TITLE
Scrolling by keyboard hangs for typescript files

### ISSUE THREAD

**Issue by rbadapanda** [R35007/font-awesome-vscode-extension#2]
Type: <b>Bug</b>

Open a moderate typescript react file in a react native project.
put the cursor on first line of the file.
Press and Hold the down arrow key.

Expected: the text cursor should repeatedly go till the bottom of the file

Actual: the text cursor gets stuck

Extension version: 3.2.1
VS Code version: Code - Insiders 1.75.0-insider (6ed4d436a9b6ae131732f4e2a723868231f4473a, 2022-12-23T05:22:56.472Z)
OS version: Darwin x64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|7, 7, 5|
|Memory (System)|16.00GB (0.26GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by R35007** [comment]
Hi @rbadapanda,

Sorry, I am not able to replicate this issue. Can you provide more info.

1. Are you sure that this is because of this Font Awesome extension?
2. Have to tried disabling all extension except Font Awesome?
3. Can you please provide a record or screenshot of the issue?

**Comment by R35007** [comment]
@rbadapanda,

Closing this for now. Please feel free to reopen this issue.
