### ISSUE TITLE
font awesome suggestions.

### ISSUE THREAD

**Issue by EHMilon** [R35007/font-awesome-vscode-extension#3]
there is no option to stop suggestions from font awesome.

**Comment by R35007** [comment]
@EHMilon, 
I have given a fix version with a setting to remove the snippet suggestion.
Please set `font-awesome.settings.showSnippetSuggestion` to false to avoid suggestions in version [3.2.2](https://marketplace.visualstudio.com/items?itemName=Thinker.font-awesome&ssr=false#overview).

Thanks :)
